## Write a Numpy program to compute the multiplication of two given matrixes

In [16]:
import numpy as np

x = np.array([[1,7,3],[9,5,8],[7,7,10]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

def dot ( x,y):
  return x.dot(y)

In [17]:
dot(x,y)

array([[ 50,  61,  72],
       [ 85, 107, 129],
       [105, 129, 153]])

## Write a NumPy program to compute the determinant of a given square array

In [8]:
def det (x):
  det = np.linalg.det(x)
  return det

In [9]:
det(x)

-160.00000000000009

## Write a NumPy program to compute the cross product of two given vectors

In [18]:
def cross (x,y):
  return np.cross(x,y)

In [19]:
cross(x,y)

array([[ 15,   0,  -5],
       [-10, -22,  25],
       [-17,   7,   7]])

## Write a NumPy program to compute the condition number of a given matrix

In [20]:
def cond (x):
  min = x[0][0]
  max = x[0][0]
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      if x[i][j] < min:
        min = x[i][j]
      if x[i][j] > max:
        max = x[i][j]
  return max/min


In [21]:
cond(x)

10.0

## Write a NumPy program to compute the inverse of a given matrix

In [10]:
def inv (x):
  inv = np.linalg.inv(x)
  return inv

In [11]:
inv(x)

array([[ 0.0375 ,  0.30625, -0.25625],
       [ 0.2125 ,  0.06875, -0.11875],
       [-0.175  , -0.2625 ,  0.3625 ]])